# Build Only for CI-Merge test to ensure the build is working for branches
trigger:
  branches:
    exclude:
    - 'master'
    - gh-pages

    pool:
      vmImage: 'Windows-latest'

    variables:
      solution: '**/src/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - checkout: self
      persistCredentials: true

    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet 6.5.0'
      inputs:
        versionSpec: 6.5.0
        checkLatest: true

    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 7.0.x'
      inputs:
        packageType: sdk
        version: 7.0.x

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) /p:Platform="$(buildPlatform)"'

    - task: replacetokens@3
      inputs:
        rootDirectory: 'templates\Dapplo.Microsoft.Extensions.Hosting.CaliburnMicro.Template\content'
        targetFiles: '*.csproj'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'fail'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'

    - script: nuget pack templates\Dapplo.Microsoft.Extensions.Hosting.CaliburnMicro.Template\Dapplo.Microsoft.Extensions.Hosting.CaliburnMicro.Template.nuspec -Version $(Build.BuildNumber)

